@startuml

!define Charcoal    #333333
!define White       #FFFFFF
!define Grey        #BBBBBB
!define Silver      #EEEEEE
!define Foregound   #666666
!define Orange      #FFE5D8
!define Blue        #DBE8F9
!define Green       #E8FBE8

skinparam Default {
  FontName          Monospaced
  FontColor         Foregound
  FontSize          12
}

skinparam Arrow {
  Color             Foregound
}

skinparam Activity {
  BackgroundColor   White
  BorderColor       Foregound
}

skinparam Swimlane {
  TitleFontColor    Charcoal
  TitleFontSize     18
  BorderColor       Grey
}

skinparam Shadowing	false

|Silver|Scenario|
|White|Client|
|Blue|Command|
|Orange|Event|
|Green|View|
|White|Provider|

@enduml
