@startuml
!include https://raw.githubusercontent.com/nserfontein/hello-event-modeling/master/tools/plantuml/detailed.puml

|GuestUI|
|ManagerUI|
|Inventory|
|Auth|
|Payment|
|Jobs|
|Providers|

'--------------

|Scenario|
:Register;
|GuestUI|
:
Username: Text
Password: Text
Register: Button
;
|Auth|
Command:Register;
Event:Registered;
detach

'--------------

|Scenario|
:Add Room;
|ManagerUI|
:
Field 1: Text
Field 2: Text
Add Room: Button
;
|Inventory|
Command:Add Room;
Event:Room Added;
View:Room Availability;
detach

'--------------

|Scenario|
:Book Room;
|GuestUI|
View:Room Availability;
:
Date: Picker
Rooms: List
Book Room: Button
;
|Inventory|
Command:Book Room;
Event:Room Booked;
View:Room Availability;
View:Cleaning Schedule;
detach

'--------------

|Scenario|
:Ready Room;
|ManagerUI|
View:Cleaning Schedule;
:
Tasks: List
Ready Room: Button
;
|Inventory|
Command:Ready Room;
Event:Room Readied;
View:Cleaning Schedule;
View:Guest Roster;
detach

'--------------

|Scenario|
:Check In;
|ManagerUI|
View:Guest Roster;
:
Field1: Text
Field2: Text
Check In: Button
;
|Inventory|
Command:Check In;
Event:Checked In;
View:Guest Roster;
detach

'--------------

|Scenario|
:Payment Request;
|GuestUI|
View:Guest Invoice;
:
Card Number: Text
Amount: Currency
Pay: Button
;
|Payment|
Command:Pay;
Event:Payment Requested;
View:Payments to Process;
detach

'--------------

|Scenario|
:Payment Succeeded;
|Jobs|
View:Payments to Process;
Job:Payment Processor;
|Payment|
Command:Process Payment;
Event:Payment Succeeded;
View:Payments to Process;
View:Sales Report;
detach

'--------------

|Scenario|
:Guest Left Hotel;
|Providers|
:
**GPS**
Lat: Text
Long: Text
;
|Inventory|
Event:GPS Update;
Command:Translate Location;
Event:Guest Left Hotel;
View:Guest Roster;
detach

'--------------

|Scenario|
:Check Out;
|Jobs|
View:Guest Roster;
Job:Checkout Processor;
|Inventory|
Command:Check Out;
Event:Checked Out;
View:Guest Roster;
detach

@enduml
