@startuml
!include https://raw.githubusercontent.com/nserfontein/hello-event-modeling/master/tools/plantuml/compact.puml

'--------------

|Scenario|
:Register;
|Client|
:
**Guest**
Username: Text
Password: Text
Register: Button
;
|Command|
:
**Auth**
Register
;
|Event|
:Registered;
detach

'--------------

|Scenario|
:Add Room;
|Client|
:
**Manager**
Field 1: Text
Field 2: Text
Add Room: Button
;
|Command|
:
**Inventory**
Add Room
;
|Event|
:Room Added;
|View|
:Room Availability;
detach

'--------------

|Scenario|
:Book Room;
|View|
:Room Availability;
|Client|
:
**Guest**
Date: Picker
Rooms: List
Book Room: Button
;
|Command|
:
**Inventory**
Book Room
;
|Event|
:Room Booked;
|View|
:Cleaning Schedule;
detach

'--------------

|Scenario|
:Ready Room;
|View|
:Cleaning Schedule;
|Client|
:
**Manager**
Tasks: List
Ready Room: Button
;
|Command|
:
**Inventory**
Ready Room
;
|Event|
:Room Readied;
|View|
:Cleaning Schedule;
:Guest Roster;
detach

'--------------

|Scenario|
:Check In;
|View|
:Guest Roster;
|Client|
:
**Manager**
Field1: Text
Field2: Text
Check In: Button
;
|Command|
:
**Inventory**
Check In
;
|Event|
:Checked In;
|View|
:Guest Roster;
detach

'--------------

|Scenario|
:Payment Request;
|Client|
:
**Guest**
Card Number: Text
Amount: Currency
Pay: Button
;
|Command|
:
**Payment**
Pay
;
|Event|
:Payment Requested;
|View|
:Payments to Process;
detach

'--------------

|Scenario|
:Payment Succeeded;
|View|
:Payments to Process;
|Client|
:Payment Processor;
|Command|
:
**Payment**
Process Payment
;
|Event|
:Payment Succeeded;
|View|
:Payments to Process;
:Sales Report;
detach

'--------------

|Scenario|
:Guest Left Hotel;
|Provider|
:
**GPS**
Lat: Text
Long: Text
;
|Command|
:
**Inventory**
Translate Location
;
|Event|
:Guest Left Hotel;
|View|
:Guest Roster;
detach

'--------------

|Scenario|
:Check Out;
|View|
:Guest Roster;
|Client|
:Checkout Processor;
|Command|
:
**Inventory**
Check Out
;
|Event|
:Checked Out;
|View|
:Guest Roster;
detach

@enduml
