@startuml
!include https://raw.githubusercontent.com/nserfontein/hello-event-modeling/master/tools/plantuml/compact.puml

' ------------------------------------
|Scenario|
:**Step1-case1**
Primary (in isolation) should properly
register itself to the provided Arbiter;
|Client|
:
**Loading...**

Create Replica
;
:**Replica**;
|Command|
:**Arbiter**
Join;
|Event|
:JoinedPrimary;
detach

' ------------------------------------
|Scenario|
:**Step1-case2**
Primary (in isolation) should react
properly to Insert, Remove, Get;
|Event|
:JoinedPrimary;
|Client|
:Get Record;
|Command|
:**Primary**
Get "k1";
|Client|
:GetResult(None);
detach

:Insert Record;
|Command|
:**Primary**
Insert "k1:v1";
|Event|
:**EventStream**
RecordInserted;


@enduml
